# Generated by Django 5.0.2 on 2024-03-15 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='user.png', upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('article_id', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkToDoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=15)),
                ('day', models.IntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('homework_to_do', models.IntegerField(default=0)),
                ('homework_done', models.IntegerField(default=0)),
                ('student_id', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='user.png', null=True, upload_to='')),
                ('marks', models.ManyToManyField(blank=True, null=True, to='base.mark')),
                ('user_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkToReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hm_files', models.ManyToManyField(blank=True, null=True, to='base.homeworktodofiles')),
                ('student_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homework', max_length=100)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('homework_id', models.UUIDField(default=uuid.UUID('4cf0046b-c7a1-41a8-83fe-58e23fb6d8a9'), editable=False)),
                ('grade', models.IntegerField(default=0)),
                ('homework_files', models.ManyToManyField(blank=True, null=True, to='base.homeworkfiles')),
                ('received_homework', models.ManyToManyField(blank=True, to='base.homeworktoreceive')),
                ('students_that_send', models.ManyToManyField(blank=True, null=True, to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('students', models.ManyToManyField(blank=True, to='base.student')),
            ],
        ),
    ]
