# Generated by Django 5.0.2 on 2024-03-02 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='user.png', null=True, upload_to='media')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('article_id', models.UUIDField(default=uuid.UUID('f5e00d9f-3f3c-496c-9c9d-135eec88544b'), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('homework_to_do', models.IntegerField(default=0)),
                ('homework_done', models.IntegerField(default=0)),
                ('student_id', models.UUIDField(default=uuid.UUID('3e3068a0-2370-4e3f-903d-baaa23038ca9'), editable=False)),
                ('image', models.ImageField(blank=True, default='user.png', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('month', models.CharField(editable=False, max_length=15)),
                ('day', models.IntegerField(default=0)),
                ('present', models.BooleanField(default=False)),
                ('student_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
