# Generated by Django 5.0.2 on 2024-03-03 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('9752e46b-1170-4013-9b7f-63e49b580a97'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('9b904a16-01de-4716-bb47-8392fdaef304'), editable=False),
        ),
        migrations.CreateModel(
            name='HomeWorkToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HomeWork', max_length=100)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('files', models.FileField(upload_to='media')),
                ('homework_id', models.UUIDField(default=uuid.UUID('894353ac-fc1c-482d-b90b-4a2f61c2f35f'), editable=False)),
                ('received_homework', models.ManyToManyField(to='base.student')),
            ],
        ),
    ]
