# Generated by Django 5.0.2 on 2024-03-03 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('dad79a85-f4c9-4c20-9cc7-a8dcc7904d51'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('fd5d19b6-1d44-48ef-9d69-9abd68d70a30'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('c5d50be6-6b95-494d-ba7a-16638fb13045'), editable=False),
        ),
    ]
