# Generated by Django 5.0.2 on 2024-03-03 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('9a030961-a647-4c87-b13f-ac00e26c4fc3'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('a0931a26-7026-4ca8-b09f-fce673290b08'), editable=False),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('f07356cd-4429-4666-b556-547406c92936'), editable=False),
        ),
    ]
