# Generated by Django 4.2.1 on 2024-02-25 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('2ca1612b-0b50-4f93-8db4-31d981b651a0'), editable=False),
        ),
    ]
