# Generated by Django 5.0.2 on 2024-03-03 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_article_id_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworktodo',
            name='files',
        ),
        migrations.AddField(
            model_name='homeworktodo',
            name='grade',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('4aa7dcca-a11b-43a3-ad41-490104f976cb'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('78dd2742-65f7-4470-9f4a-209466222bb1'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('dcbff746-b544-4caf-a1f0-18f104f706f4'), editable=False),
        ),
        migrations.CreateModel(
            name='HomeWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='media')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.homeworktodo')),
            ],
        ),
    ]
