# Generated by Django 5.0.2 on 2024-03-03 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('e1a86d5a-9d89-4428-a1ad-d69b91cb28a7'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('00ec80e5-cd96-4146-9896-10aa5556f6ef'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('c78ceb7e-6b02-4a08-98a9-0ab97fc70301')),
        ),
    ]
