# Generated by Django 5.0.2 on 2024-03-03 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_homeworktodo_files_homeworktodo_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('b8be3a19-1494-495e-96fe-629aa199bfd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('53e89eed-5ed0-4b69-bd10-75cb806fa7e5'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('e8b074c8-79e4-4558-bc0b-56f8eeba7bef'), editable=False),
        ),
    ]
