# Generated by Django 4.2.1 on 2024-02-25 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('aadb3b4d-750a-4d4a-ac88-73996c2f9739'), editable=False),
        ),
    ]
