# Generated by Django 5.0.2 on 2024-03-01 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('b17ef19b-979f-47a9-abfd-22fc3f3655d9'), editable=False),
        ),
    ]
