# Generated by Django 5.0.2 on 2024-03-03 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_article_article_id_alter_classroom_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('646f3ddf-1e84-4ec9-ad75-de64de40eedd'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('7980078b-d319-481f-b602-9d145f184eeb'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('e56a1679-8878-409c-9ed0-609250327eb4')),
        ),
    ]
