# Generated by Django 5.0.2 on 2024-03-01 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('9b074ae5-6eff-4c07-95f0-f85a76a1813a'), editable=False),
        ),
    ]
