# Generated by Django 5.0.2 on 2024-03-05 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_mark_student_obj_student_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('1a974a79-a5fb-487e-942b-91b65aa4040a'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('620cf152-3aeb-4c31-b8c1-ddf9aac8d9bf'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.ManyToManyField(blank=True, null=True, to='base.mark'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('e4873992-db10-11ee-af3d-5b1fde1d6fb2')),
        ),
    ]
