# Generated by Django 5.0.2 on 2024-03-01 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('fc6a0c84-6735-44a2-add2-7d9ece9ffd0e'), editable=False),
        ),
    ]
