# Generated by Django 5.0.2 on 2024-03-01 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('74697883-ddaf-46d7-a43e-09d1c580784f'), editable=False),
        ),
    ]
