# Generated by Django 5.0.2 on 2024-03-05 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('1ae84f12-155a-4287-888f-2233a7c4f0f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('8054cf05-272e-43c3-81bf-19c055b1434b'), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('eee9d39a-db10-11ee-af3d-5b1fde1d6fb2')),
        ),
    ]
