# Generated by Django 5.0.2 on 2024-03-01 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('55deefca-750f-4bdf-8fa3-1f7e871d8921'), editable=False),
        ),
    ]
