# Generated by Django 5.0.2 on 2024-03-06 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('211dfb78-8b04-4a32-be70-beb3adb4041a'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('068a92d6-6d79-48cf-84ca-05a216669321'), editable=False),
        ),
    ]
