# Generated by Django 5.0.2 on 2024-03-01 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('80de9eba-77da-4e23-bd63-c16e0047e8e5'), editable=False),
        ),
    ]
