# Generated by Django 5.0.2 on 2024-03-06 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkfiles',
            name='id_of_student',
            field=models.CharField(blank=True, default='Homework', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('ef964aab-5997-4587-b59b-decbb7f5c3b3'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworkfiles',
            name='files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('ee0aaf6c-8c78-4a63-97ef-24dffeef293a'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='title',
            field=models.CharField(default='Homework', max_length=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='month',
            field=models.CharField(max_length=15),
        ),
    ]
