# Generated by Django 5.0.2 on 2024-03-06 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_homeworkfiles_id_of_student_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkfiles',
            name='id_of_student',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('2883f4ec-dbb3-41ef-a6d0-f32d9dfedd5d'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('86ba053b-4714-4c47-b572-6b0b406ad046'), editable=False),
        ),
    ]
