# Generated by Django 5.0.2 on 2024-03-06 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_homeworkfiles_id_of_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkfiles',
            name='homework',
        ),
        migrations.AddField(
            model_name='homeworktodo',
            name='homework_files',
            field=models.ManyToManyField(blank=True, null=True, to='base.homeworkfiles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('302fe254-be07-4f41-8275-782e1d30ce87'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('e33ad4cc-c04d-4c66-ab4c-c33fe7ec5215'), editable=False),
        ),
    ]
