# Generated by Django 5.0.2 on 2024-03-07 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_homeworkfiles_homework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkToDoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('b4b014a9-afbf-44bf-991e-6319c9b5e4cc'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('a1178c3f-9dd6-46fe-a344-b1e14faae96d'), editable=False),
        ),
        migrations.CreateModel(
            name='HomeworkToReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hm_files', models.ManyToManyField(blank=True, null=True, to='base.homeworktodofiles')),
                ('student_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='received_homework',
            field=models.ManyToManyField(blank=True, to='base.homeworktoreceive'),
        ),
    ]
