# Generated by Django 5.0.2 on 2024-03-08 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_homeworktodofiles_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktodo',
            name='students_that_send',
            field=models.ManyToManyField(blank=True, null=True, to='base.student'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.UUIDField(default=uuid.UUID('0dd51c19-ad5f-4e4c-83a3-628a8d341755'), editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('86c9e637-23be-4449-b130-06b8829bfc19'), editable=False),
        ),
    ]
