# Generated by Django 5.0.2 on 2024-03-08 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_homeworktodo_students_that_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(editable=False),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('02ed45c8-350e-4dde-954c-b4043fe5b294'), editable=False),
        ),
    ]
