# Generated by Django 5.0.2 on 2024-03-10 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('df3d17dd-41bd-43e8-a59c-3e55c82d732a'), editable=False),
        ),
    ]
