# Generated by Django 5.0.2 on 2024-03-11 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_article_image_alter_homeworktodo_homework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('dc84a5e2-fecb-4826-aaa5-4727d992b9aa'), editable=False),
        ),
    ]
