# Generated by Django 5.0.2 on 2024-03-14 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_article_article_id_alter_homeworktodo_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('7e50caf4-0920-44b2-a688-5c5259e7ca0f'), editable=False),
        ),
    ]
