# Generated by Django 5.0.2 on 2024-03-14 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_homeworktodo_homework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('b4985173-5871-4e34-8ac8-093e505b1888'), editable=False),
        ),
    ]
