# Generated by Django 5.0.2 on 2024-03-14 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_homeworktodo_homework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktodo',
            name='homework_id',
            field=models.UUIDField(default=uuid.UUID('7c6fb0fc-295c-41e2-a6bb-2501b86f8f98'), editable=False),
        ),
    ]
